const items = [{
            "name": "Glucose",
            "description": '',
            "category": "Blood Glucose",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 65,
            "optMin": 75,
            "optMax": 86,
            "refMax": 99
        },
        {
            "name": "Hemoglobin A1C",
            "description": '',
            "category": "Blood Glucose",
            "sex": "",
            "unit": "%",
            "refMin": 0,
            "optMin": 4.5,
            "optMax": 5.5,
            "refMax": 5.7
        },
        {
            "name": "Insulin - Fasting",
            "description": '',
            "category": "Blood Glucose",
            "sex": "",
            "unit": "µIU/mL",
            "refMin": 2,
            "optMin": 2,
            "optMax": 5,
            "refMax": 19
        },
        {
            "name": "Fructosamine",
            "description": '',
            "category": "Blood Glucose",
            "sex": "",
            "unit": "µmol/L",
            "refMin": 190,
            "optMin": 190,
            "optMax": 228,
            "refMax": 270
        },
        {
            "name": "C-Peptide",
            "description": '',
            "category": "Blood Glucose",
            "sex": "",
            "unit": "ng/mL",
            "refMin": 0.8,
            "optMin": 1.1,
            "optMax": 1.6,
            "refMax": 3.1
        },
        {
            "name": "Collagen Cross-Linked NTx",
            "description": '',
            "category": "Bone",
            "sex": "",
            "unit": "nmolBCE/mmolcreat",
            "refMin": 5,
            "optMin": 5,
            "optMax": 79,
            "refMax": 79
        },
        {
            "name": "RBC",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "M",
            "unit": "m/cumm",
            "refMin": 4.2,
            "optMin": 4.2,
            "optMax": 4.9,
            "refMax": 5.8
        },
        {
            "name": "RBC",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "F",
            "unit": "m/cumm",
            "refMin": 3.8,
            "optMin": 3.9,
            "optMax": 4.5,
            "refMax": 5.1
        },
        {
            "name": "Hemoglobin",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "M",
            "unit": "g/dL",
            "refMin": 13.2,
            "optMin": 14,
            "optMax": 15,
            "refMax": 17.1
        },
        {
            "name": "Hemoglobin",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "F",
            "unit": "g/dL",
            "refMin": 11.7,
            "optMin": 13.5,
            "optMax": 14.5,
            "refMax": 15.5
        },
        {
            "name": "Hematocrit",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "M",
            "unit": "%",
            "refMin": 38.5,
            "optMin": 40,
            "optMax": 48,
            "refMax": 50
        },
        {
            "name": "Hematocrit",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "F",
            "unit": "%",
            "refMin": 35,
            "optMin": 37,
            "optMax": 44,
            "refMax": 45
        },
        {
            "name": "MCV",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "",
            "unit": "fL",
            "refMin": 80,
            "optMin": 82,
            "optMax": 89.9,
            "refMax": 100
        },
        {
            "name": "MCH",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "",
            "unit": "pg",
            "refMin": 27,
            "optMin": 28,
            "optMax": 31.9,
            "refMax": 33
        },
        {
            "name": "MCHC",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "",
            "unit": "g/dL",
            "refMin": 32,
            "optMin": 32,
            "optMax": 35,
            "refMax": 36
        },
        {
            "name": "Platelets",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "",
            "unit": "k/cumm",
            "refMin": 140,
            "optMin": 155,
            "optMax": 385,
            "refMax": 400
        },
        {
            "name": "RDW",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "",
            "unit": "%",
            "refMin": 11,
            "optMin": 11.7,
            "optMax": 13,
            "refMax": 15
        },
        {
            "name": "Reticulocyte count",
            "description": '',
            "category": "CBC/Hemoatology",
            "sex": "",
            "unit": "%",
            "refMin": 0.5,
            "optMin": 0.1,
            "optMax": 1.5,
            "refMax": 1.5
        },
        {
            "name": "Sodium",
            "description": '',
            "category": "Electrolytes",
            "sex": "",
            "unit": "mEq/L",
            "refMin": 135,
            "optMin": 135,
            "optMax": 142,
            "refMax": 146
        },
        {
            "name": "Potassium",
            "description": '',
            "category": "Electrolytes",
            "sex": "",
            "unit": "mEq/L",
            "refMin": 3.5,
            "optMin": 4,
            "optMax": 4.5,
            "refMax": 5.3
        },
        {
            "name": "Sodium/Potassium Ratio",
            "description": '',
            "category": "Electrolytes",
            "sex": "",
            "unit": "ratio",
            "refMin": 30,
            "optMin": 30,
            "optMax": 35,
            "refMax": 35
        },
        {
            "name": "Chloride",
            "description": '',
            "category": "Electrolytes",
            "sex": "",
            "unit": "mEq/L",
            "refMin": 98,
            "optMin": 100,
            "optMax": 106,
            "refMax": 110
        },
        {
            "name": "CO2",
            "description": '',
            "category": "Electrolytes",
            "sex": "",
            "unit": "mEq/L",
            "refMin": 19,
            "optMin": 25,
            "optMax": 30,
            "refMax": 30
        },
        {
            "name": "DHEA-S",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "µg/dL",
            "refMin": 65,
            "optMin": 350,
            "optMax": 490,
            "refMax": 510
        },
        {
            "name": "DHEA-S",
            "description": '',
            "category": "Hormones",
            "sex": "F",
            "unit": "µg/dL",
            "refMin": 18,
            "optMin": 275,
            "optMax": 390,
            "refMax": 390
        },
        {
            "name": "Testosterone Total",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "ng/dL",
            "refMin": 250,
            "optMin": 700,
            "optMax": 900,
            "refMax": 1100
        },
        {
            "name": "Testosterone Total",
            "description": '',
            "category": "Hormones",
            "sex": "F",
            "unit": "ng/dL",
            "refMin": 2,
            "optMin": 35,
            "optMax": 45,
            "refMax": 45
        },
        {
            "name": "Testosterone - Free",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "pg/mL",
            "refMin": 46,
            "optMin": 150,
            "optMax": 224,
            "refMax": 224
        },
        {
            "name": "Testosterone - Bioavailable",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "ng/dL",
            "refMin": 110,
            "optMin": 375,
            "optMax": 575,
            "refMax": 575
        },
        {
            "name": "Testosterone - Bioavailable",
            "description": '',
            "category": "Hormones",
            "sex": "F",
            "unit": "ng/dL",
            "refMin": 0.5,
            "optMin": 5.5,
            "optMax": 8.5,
            "refMax": 8.5
        },
        {
            "name": "Testosterone Free - LABCORP",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "pg/mL",
            "refMin": 9.3,
            "optMin": 20,
            "optMax": 25,
            "refMax": 26.5
        },
        {
            "name": "Testosterone Free",
            "description": '',
            "category": "Hormones",
            "sex": "F",
            "unit": "pg/mL",
            "refMin": 0.2,
            "optMin": 1,
            "optMax": 2.2,
            "refMax": 5
        },
        {
            "name": "Sex Hormone Binding Globulin",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "nmol/L",
            "refMin": 10,
            "optMin": 30,
            "optMax": 40,
            "refMax": 50
        },
        {
            "name": "Sex Hormone Binding Globulin",
            "description": '',
            "category": "Hormones",
            "sex": "F",
            "unit": "nmol/L",
            "refMin": 10,
            "optMin": 30,
            "optMax": 40,
            "refMax": 50
        },
        {
            "name": "Estradiol",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "pg/mL",
            "refMin": 0,
            "optMin": 20,
            "optMax": 30,
            "refMax": 39
        },
        {
            "name": "Estradiol",
            "description": '',
            "category": "Hormones",
            "sex": "F",
            "unit": "pg/mL",
            "refMin": 19,
            "optMin": 150,
            "optMax": 350,
            "refMax": 357
        },
        {
            "name": "Progesterone",
            "description": '',
            "category": "Hormones",
            "sex": "M",
            "unit": "ng/mL",
            "refMin": 0.2,
            "optMin": 1,
            "optMax": 1.2,
            "refMax": 1.3
        },
        {
            "name": "Progesterone",
            "description": '',
            "category": "Hormones",
            "sex": "F",
            "unit": "ng/mL",
            "refMin": 2.6,
            "optMin": 18,
            "optMax": 27,
            "refMax": 27
        },
        {
            "name": "Cortisol - AM",
            "description": '',
            "category": "Hormones",
            "sex": "",
            "unit": "µg/dL",
            "refMin": 4,
            "optMin": 10,
            "optMax": 15,
            "refMax": 22
        },
        {
            "name": "Cortisol - PM",
            "description": '',
            "category": "Hormones",
            "sex": "",
            "unit": "µg/dL",
            "refMin": 3,
            "optMin": 6,
            "optMax": 10,
            "refMax": 17
        },
        {
            "name": "Gastrin",
            "description": '',
            "category": "Hormones",
            "sex": "",
            "unit": "pg/mL",
            "refMin": 0,
            "optMin": 45,
            "optMax": 90,
            "refMax": 100
        },
        {
            "name": "Hs CRP",
            "description": '',
            "category": "Inflammation/Oxidation",
            "sex": "M",
            "unit": "mg/L",
            "refMin": 0,
            "optMin": 0,
            "optMax": 0.6,
            "refMax": 2.9
        },
        {
            "name": "Hs CRP",
            "description": '',
            "category": "Inflammation/Oxidation",
            "sex": "F",
            "unit": "mg/L",
            "refMin": 0,
            "optMin": 0,
            "optMax": 1.5,
            "refMax": 2.9
        },
        {
            "name": "C-Reactive Protein",
            "description": '',
            "category": "Inflammation/Oxidation",
            "sex": "",
            "unit": "mg/L",
            "refMin": 0,
            "optMin": 0,
            "optMax": 4.5,
            "refMax": 7.9
        },
        {
            "name": "ESR",
            "description": '',
            "category": "Inflammation/Oxidation",
            "sex": "M",
            "unit": "mm/hr",
            "refMin": 0,
            "optMin": 0,
            "optMax": 5,
            "refMax": 15
        },
        {
            "name": "ESR",
            "description": '',
            "category": "Inflammation/Oxidation",
            "sex": "F",
            "unit": "mm/hr",
            "refMin": 0,
            "optMin": 0,
            "optMax": 10,
            "refMax": 20
        },
        {
            "name": "Homocysteine",
            "description": '',
            "category": "Inflammation/Oxidation",
            "sex": "",
            "unit": "µmol/L",
            "refMin": 0,
            "optMin": 0,
            "optMax": 7.2,
            "refMax": 10.3
        },
        {
            "name": "Fibrinogen",
            "description": '',
            "category": "Inflammation/Oxidation",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 175,
            "optMin": 200,
            "optMax": 300,
            "refMax": 425
        },
        {
            "name": "Iron - Serum",
            "description": '',
            "category": "Iron Markers",
            "sex": "",
            "unit": "µg/dL",
            "refMin": 40,
            "optMin": 85,
            "optMax": 130,
            "refMax": 160
        },
        {
            "name": "Ferritin",
            "description": '',
            "category": "Iron Markers",
            "sex": "",
            "unit": "ng/mL",
            "refMin": 10,
            "optMin": 30,
            "optMax": 70,
            "refMax": 232
        },
        {
            "name": "TIBC",
            "description": '',
            "category": "Iron Markers",
            "sex": "",
            "unit": "µg/dL",
            "refMin": 250,
            "optMin": 250,
            "optMax": 350,
            "refMax": 425
        },
        {
            "name": "% Transferrin saturation",
            "description": '',
            "category": "Iron Markers",
            "sex": "",
            "unit": "%",
            "refMin": 15,
            "optMin": 20,
            "optMax": 35,
            "refMax": 50
        },
        {
            "name": "Cholesterol - Total",
            "description": '',
            "category": "Lipids",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 125,
            "optMin": 160,
            "optMax": 180,
            "refMax": 200
        },
        {
            "name": "Triglycerides",
            "description": '',
            "category": "Lipids",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 0,
            "optMin": 70,
            "optMax": 80,
            "refMax": 150
        },
        {
            "name": "LDL Cholesterol",
            "description": '',
            "category": "Lipids",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 0,
            "optMin": 0,
            "optMax": 120,
            "refMax": 130
        },
        {
            "name": "HDL Cholesterol",
            "description": '',
            "category": "Lipids",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 46,
            "optMin": 55,
            "optMax": 70,
            "refMax": 100
        },
        {
            "name": "VLDL Cholesterol",
            "description": '',
            "category": "Lipids",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 0,
            "optMin": 0,
            "optMax": 10,
            "refMax": 29
        },
        {
            "name": "Cholesterol/HDL Ratio",
            "description": '',
            "category": "Lipids",
            "sex": "",
            "unit": "Ratio",
            "refMin": 0,
            "optMin": 0,
            "optMax": 3,
            "refMax": 5
        },
        {
            "name": "Triglyceride/HDL Ratio",
            "description": '',
            "category": "Lipids",
            "sex": "",
            "unit": "ratio",
            "refMin": 0,
            "optMin": 0,
            "optMax": 2,
            "refMax": 2
        },
        {
            "name": "Alk Phos",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "IU/L",
            "refMin": 35,
            "optMin": 70,
            "optMax": 100,
            "refMax": 115
        },
        {
            "name": "AST (SGOT)",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "IU/L",
            "refMin": 10,
            "optMin": 10,
            "optMax": 26,
            "refMax": 35
        },
        {
            "name": "ALT (SGPT)",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "IU/L",
            "refMin": 6,
            "optMin": 10,
            "optMax": 26,
            "refMax": 29
        },
        {
            "name": "LDH",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "IU/L",
            "refMin": 120,
            "optMin": 140,
            "optMax": 200,
            "refMax": 250
        },
        {
            "name": "Bilirubin - Total",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 0.2,
            "optMin": 0.1,
            "optMax": 0.9,
            "refMax": 1.2
        },
        {
            "name": "Bilirubin - Direct",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 0,
            "optMin": 0,
            "optMax": 0.2,
            "refMax": 0.2
        },
        {
            "name": "Bilirubin - Indirect",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 0.2,
            "optMin": 0.1,
            "optMax": 0.7,
            "refMax": 1.2
        },
        {
            "name": "GGT",
            "description": '',
            "category": "Liver and Gallbladder",
            "sex": "",
            "unit": "IU/L",
            "refMin": 3,
            "optMin": 10,
            "optMax": 30,
            "refMax": 70
        },
        {
            "name": "Anion gap",
            "description": '',
            "category": "Metabolic",
            "sex": "",
            "unit": "mEq/L",
            "refMin": 6,
            "optMin": 7,
            "optMax": 12,
            "refMax": 16
        },
        {
            "name": "Uric Acid",
            "description": '',
            "category": "Metabolic",
            "sex": "M",
            "unit": "mg/dL",
            "refMin": 3.5,
            "optMin": 3.5,
            "optMax": 5.9,
            "refMax": 8
        },
        {
            "name": "Uric Acid",
            "description": '',
            "category": "Metabolic",
            "sex": "F",
            "unit": "mg/dL",
            "refMin": 2.5,
            "optMin": 3,
            "optMax": 5.5,
            "refMax": 7
        },
        {
            "name": "Leptin",
            "description": '',
            "category": "Metabolic",
            "sex": "M",
            "unit": "ng/mL",
            "refMin": 0.3,
            "optMin": 1.2,
            "optMax": 9.5,
            "refMax": 13.4
        },
        {
            "name": "Laptin",
            "description": '',
            "category": "Metabolic",
            "sex": "F",
            "unit": "ng/mL",
            "refMin": 4.7,
            "optMin": 4.1,
            "optMax": 25,
            "refMax": 23.7
        },
        {
            "name": "Calcium",
            "description": '',
            "category": "Minerals",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 8.6,
            "optMin": 9.2,
            "optMax": 10,
            "refMax": 10.4
        },
        {
            "name": "Calcium/Albumin Ratio",
            "description": '',
            "category": "Minerals",
            "sex": "",
            "unit": "ratio",
            "refMin": 0,
            "optMin": 0,
            "optMax": 2.6,
            "refMax": 2.6
        },
        {
            "name": "Phosphorus",
            "description": '',
            "category": "Minerals",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 2.5,
            "optMin": 3,
            "optMax": 4,
            "refMax": 4.5
        },
        {
            "name": "Calcium/Phosphorus Ratio",
            "description": '',
            "category": "Minerals",
            "sex": "",
            "unit": "ratio",
            "refMin": 2.3,
            "optMin": 2.3,
            "optMax": 2.7,
            "refMax": 2.7
        },
        {
            "name": "Magnesium",
            "description": '',
            "category": "Minerals",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 1.5,
            "optMin": 2.2,
            "optMax": 2.5,
            "refMax": 2.5
        },
        {
            "name": "Creatine Kinase",
            "description": '',
            "category": "Muscle",
            "sex": "",
            "unit": "u/l",
            "refMin": 44,
            "optMin": 65,
            "optMax": 135,
            "refMax": 196
        },
        {
            "name": "PSA - Total",
            "description": '',
            "category": "Prostate",
            "sex": "",
            "unit": "ng/mL",
            "refMin": 0,
            "optMin": 0,
            "optMax": 2.6,
            "refMax": 4
        },
        {
            "name": "Protein - Total",
            "description": '',
            "category": "Proteins",
            "sex": "",
            "unit": "g/dL",
            "refMin": 6.1,
            "optMin": 6.9,
            "optMax": 7.4,
            "refMax": 8.1
        },
        {
            "name": "Albumin",
            "description": '',
            "category": "Proteins",
            "sex": "",
            "unit": "g/dL",
            "refMin": 3.6,
            "optMin": 4,
            "optMax": 5,
            "refMax": 5.1
        },
        {
            "name": "Globulin - Total",
            "description": '',
            "category": "Proteins",
            "sex": "",
            "unit": "g/dL",
            "refMin": 1.9,
            "optMin": 2.4,
            "optMax": 2.8,
            "refMax": 3.7
        },
        {
            "name": "Albumin/Globulin Ratio",
            "description": '',
            "category": "Proteins",
            "sex": "",
            "unit": "ratio",
            "refMin": 1,
            "optMin": 1.4,
            "optMax": 2.1,
            "refMax": 2.5
        },
        {
            "name": "BUN",
            "description": '',
            "category": "Renal",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 7,
            "optMin": 10,
            "optMax": 16,
            "refMax": 25
        },
        {
            "name": "Creatinine",
            "description": '',
            "category": "Renal",
            "sex": "",
            "unit": "mg/dL",
            "refMin": 0.4,
            "optMin": 0.8,
            "optMax": 1.1,
            "refMax": 1.5
        },
        {
            "name": "BUN/Creatinine Ratio",
            "description": '',
            "category": "Renal",
            "sex": "",
            "unit": "Ratio",
            "refMin": 6,
            "optMin": 10,
            "optMax": 16,
            "refMax": 22
        },
        {
            "name": "eGFR Non-Afr. American",
            "description": '',
            "category": "Renal",
            "sex": "",
            "unit": "mL/min/1.73m2",
            "refMin": 60,
            "optMin": 90,
            "optMax": 120,
            "refMax": 120
        },
        {
            "name": "eGFR African American",
            "description": '',
            "category": "Renal",
            "sex": "",
            "unit": "mL/min/1.73m2",
            "refMin": 60,
            "optMin": 90,
            "optMax": 120,
            "refMax": 120
        },
        {
            "name": "Creatinine Clearance",
            "description": '',
            "category": "Renal",
            "sex": "",
            "unit": "g/24hours",
            "refMin": 75,
            "optMin": 85,
            "optMax": 115,
            "refMax": 125
        },
        {
            "name": "TSH",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "µU/mL",
            "refMin": 0.4,
            "optMin": 1.3,
            "optMax": 3,
            "refMax": 4.5
        },
        {
            "name": "Free T3",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "pg/mL",
            "refMin": 2.3,
            "optMin": 3,
            "optMax": 3.5,
            "refMax": 4.2
        },
        {
            "name": "Total T3",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "ng/dL",
            "refMin": 76,
            "optMin": 90,
            "optMax": 168,
            "refMax": 181
        },
        {
            "name": "Free T4",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "ng/dL",
            "refMin": 0.8,
            "optMin": 1,
            "optMax": 1.5,
            "refMax": 1.8
        },
        {
            "name": "Total T4",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "µg/dL",
            "refMin": 4.5,
            "optMin": 6,
            "optMax": 11.9,
            "refMax": 12
        },
        {
            "name": "T3 Uptake",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "%",
            "refMin": 22,
            "optMin": 27,
            "optMax": 35,
            "refMax": 37
        },
        {
            "name": "Reverse T3",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "ng/dL",
            "refMin": 8,
            "optMin": 10,
            "optMax": 25,
            "refMax": 25
        },
        {
            "name": "Free Thyroxine Index (T7)",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "Index",
            "refMin": 1.4,
            "optMin": 1.7,
            "optMax": 4.6,
            "refMax": 3.8
        },
        {
            "name": "Thyroid Peroxidase (TPO) Abs",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "IU/mL",
            "refMin": 0,
            "optMin": 0,
            "optMax": 6.8,
            "refMax": 9
        },
        {
            "name": "Thyroid Peroxidase (TPO) Abs LABCORP",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "IU/mL",
            "refMin": 0,
            "optMin": 0,
            "optMax": 34,
            "refMax": 34
        },
        {
            "name": "Thyroglobulin Abs",
            "description": '',
            "category": "Thyroid",
            "sex": "",
            "unit": "IU/mL",
            "refMin": 0,
            "optMin": 0,
            "optMax": 1,
            "refMax": 1
        },
        {
            "name": "Vitamin D (25-OH)",
            "description": '',
            "category": "Vitamins",
            "sex": "",
            "unit": "ng/mL",
            "refMin": 20,
            "optMin": 50,
            "optMax": 100,
            "refMax": 100
        },
        {
            "name": "Vitamin B12",
            "description": '',
            "category": "Vitamins",
            "sex": "",
            "unit": "pg/mL",
            "refMin": 200,
            "optMin": 450,
            "optMax": 800,
            "refMax": 1100
        },
        {
            "name": "Folate",
            "description": '',
            "category": "Vitamins",
            "sex": "",
            "unit": "ng/mL",
            "refMin": 5.5,
            "optMin": 15,
            "optMax": 25,
            "refMax": 27
        },
        {
            "name": "Total WBCs",
            "description": '',
            "category": "White Blood Cells",
            "sex": "",
            "unit": "k/cumm",
            "refMin": 3.8,
            "optMin": 5.5,
            "optMax": 7.5,
            "refMax": 10.8
        },
        {
            "name": "Neutrophils",
            "description": '',
            "category": "White Blood Cells",
            "sex": "",
            "unit": "%",
            "refMin": 38,
            "optMin": 40,
            "optMax": 60,
            "refMax": 74
        },
        {
            "name": "Bands",
            "description": '',
            "category": "White Blood Cells",
            "sex": "",
            "unit": "%",
            "refMin": 0,
            "optMin": 0,
            "optMax": 5,
            "refMax": 5
        },
        {
            "name": "Lymphocytes",
            "description": '',
            "category": "White Blood Cells",
            "sex": "",
            "unit": "%",
            "refMin": 14,
            "optMin": 24,
            "optMax": 44,
            "refMax": 46
        },
        {
            "name": "Monocytes",
            "description": '',
            "category": "White Blood Cells",
            "sex": "",
            "unit": "%",
            "refMin": 4,
            "optMin": 0,
            "optMax": 7,
            "refMax": 13
        },
        {
            "name": "Eosinophils",
            "description": '',
            "category": "White Blood Cells",
            "sex": "",
            "unit": "%",
            "refMin": 0,
            "optMin": 0,
            "optMax": 3,
            "refMax": 3
        },
        {
            "name": "Basophils",
            "description": '',
            "category": "White Blood Cells",
            "sex": "",
            "unit": "%",
            "refMin": 0,
            "optMin": 0,
            "optMax": 1,
            "refMax": 1
        }
    ];

export default items;